---
- name: Incluye el archivo con las variables
  ansible.builtin.include_vars:
    file: vars_main.yml

- name: Instalar dependencias para s3cmd
  ansible.builtin.package:
    name: "{{ item }}"
    update_cache: true
    cache_valid_time: 3600
  with_items: "{{ s3cmd_packages }}"

- name: Descargar s3cmd y descomprimir
  ansible.builtin.unarchive:
    src: "{{ s3cmd_url }}"
    dest: "/opt/"
    remote_src: true

- name: Instalando s3cmd via python
  ansible.builtin.shell:
    cmd: |
      cd /opt/s3cmd-2.3.0/
      /usr/bin/python3 setup.py install
  changed_when: false

- name: Crear archivo con credenciales para "{{ s3fs_bucket }}"
  ansible.builtin.template:
    src: "files/{{ s3cmd_creds }}.j2"
    dest: "/etc/{{ s3cmd_creds }}-{{ s3fs_bucket }}"
    mode: 0644

